name: togu_yemekhane
description: TOGU Yemekhane
publish_to: "none"
version: 2.0.0+15

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
