name: togu_yemekhane
description: TOGU Yemekhane.
publish_to: "none"
version: 1.1.2+13

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.19.0
  package_info_plus: ^7.0.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
